nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: Esta es una App de prueba!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
